sistema_valledor/cliente/urls.py
from django.urls import path
from .views import Panel_Cliente, Listar_Productos, Detalle_Productos, Listado_Locales, Detalle_Locales, \
    Listar_Productos_Tiendas, Mis_Listas, Detalle_Listas, Agregar_Listas, Actualizar_Listas, Eliminar_Listas, \
    Eliminar_Productos_Listas, Actualizar_Productos_Listas, Detalle_lista_success, Seleccion_Reportes, Reporte_Pedidos


cliente_urlpatterns = ([
    path('panel_cliente/<int:id>/', Panel_Cliente, name="panel_cliente"),
    path('listar_productos/', Listar_Productos, name="listar_productos"),
    path('detalle_productos/<int:id>/', Detalle_Productos, name="detalle_productos"),
    path('listado_locales/', Listado_Locales, name="listado_locales"),
    path('detalle_locales/<int:id>/', Detalle_Locales, name="detalle_locales"),
    path('listar_productos_tiendas/<int:id>/', Listar_Productos_Tiendas, name="listar_productos_tiendas"),
    path('mis_listas/<int:id>/', Mis_Listas, name="mis_listas"),
    path('detalle_listas/<int:id>/', Detalle_Listas, name="detalle_listas"),
    path('success_detalle_lista/<int:id>/',Detalle_lista_success , name = "detalle_lista_ok"),
    path('agregar_lista/', Agregar_Listas, name="agregar_lista"),
    path('actualizar_lista/<int:id>/', Actualizar_Listas, name="actualizar_lista"),
    path('eliminar_lista/<int:id>/', Eliminar_Listas, name="eliminar_lista"),
    path('detalle_listas/<int:id_lista>/eliminar_producto_lista/<int:id_prod>',Eliminar_Productos_Listas, name="eliminar_producto_lista"),
    path('detalle_listas/<int:id_lista>/actualizar_producto_lista/<int:id_prod>',Actualizar_Productos_Listas, name="actualizar_producto_lista"),
    path('reporte_pedidos/<int:id_user>/', Reporte_Pedidos, name = "reporte_pedidos"),
    path('seccion_reportes/<int:id_user>/', Seleccion_Reportes, name = "reportes"),
    ],'cliente')

sistema_valledor/core/urls.py
from django.urls import path
from .views import index,contactanos

core_patterns = ([
path("",index, name = "index"),
path("contactanos/",contactanos, name = "contactanos"),
],'core')

sistema_valledor/sistema_valledor/urls.py
from django.contrib import admin
from django.urls import path, include
from core.urls import core_patterns
from registration.urls import registration_urlpatterns
from vendedor.urls import vendedor_urlpatterns
from cliente.urls import cliente_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(registration_urlpatterns)),
    path('cliente/', include(cliente_urlpatterns)),
    path('vendedor/', include(vendedor_urlpatterns)),
    path('',include(core_patterns)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sistema_valledor/cliente/models.py
#Inicial
from django.db import models
from vendedor.models import Local, Productos
#Traer el modelo de Usuarios
from django.contrib.auth.models import User
from registration.models import Tipo_usuarios

# Create your models here.
class Listas(models.Model):
    estados_de_listas = (('lista_retiro', 'Listo para retirar'), ('armando_pedido', 'Armando Pedido'), ('normal', 'Normal'),
                         ('enviada', 'Enviada'), ('cancelada', 'Cancelada'),
                          ('no_retirada', 'No retirada'),('completada', 'Lista completada'))
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(verbose_name="Nombre de la lista", null=True, blank=True, max_length=50)
    total = models.PositiveIntegerField(verbose_name="Total de la lista", null=True, blank=True, default=0)
    fecha_enviado = models.DateField(verbose_name="Fecha de envio de la lista", null=True, blank=True)
    fecha_expiracion = models.DateField(verbose_name="Fecha de expiracion de la lista", null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(verbose_name="Fecha de actualizacion de la lista", null=True, blank=True, auto_now=True)
    comentario_cliente = models.TextField(verbose_name="Comentario de cliente", null=True, blank=True)
    comentario_vendedor = models.TextField(verbose_name="Comentario de vendedor", null=True, blank=True)
    estado_lista = models.CharField(verbose_name="Estado de la lista", max_length=20, null=True, blank=True, choices=estados_de_listas, default='normal')
    cancelaciones = models.PositiveIntegerField(verbose_name = "Veces restantes a cancelar la lista", null=True, blank=True, default=5)
    total_marcado = models.PositiveIntegerField(verbose_name="Total de los productos marcados", null=True, blank=True, default=0)
    valorizacion = models.BooleanField(verbose_name="Fue Valorizada?",null= True, blank=True, default=False)

    class Meta:
        verbose_name = "Listas"
        verbose_name_plural = "Listas"

    def __str__(self):
        return self.nombre

class Productos_listas(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True )
    productos = models.ForeignKey(Productos, on_delete=models.CASCADE, null=True, blank=True )
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True )
    lista = models.ForeignKey(Listas, on_delete=models.CASCADE, null=True, blank=True )
    cantidad = models.PositiveIntegerField(verbose_name="Cantidad a comprar", null=True, blank=True, default=0)
    comentarios = models.TextField(verbose_name="Comentarios del productos a comprar", null=True, blank=True)
    precio_producto = models.PositiveIntegerField(verbose_name="Precio actual del producto a comprar", null=True, blank=True, default=0)
    producto_marcado = models.BooleanField(verbose_name="Producto marcado", null=True, blank=True, default=False)
    oferta = models.BooleanField(verbose_name="Producto en Oferta", null=True, blank=True, default=False)

    class Meta:
        verbose_name = "Producto de la lista"
        verbose_name_plural = "Productos de las listas"

    def __str__(self):
        return "{}, perteneciente al local {}".format(self.productos.nombre, self.local.nombre_local)

#Reporteria para clientes
class Reporte_listas(models.Model):
    lista = models.PositiveIntegerField(verbose_name="ID lista", default=0, null=True, blank=True)
    local = models.ForeignKey(Local, on_delete= models.CASCADE, null = True, blank = True)
    nombre_lista = models.CharField(verbose_name="Nombre de la lista", max_length=50, null=True, blank=True)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)
    total = models.PositiveIntegerField(verbose_name="Total del pedido", null = True, blank=True)
    cantidad_items = models.PositiveIntegerField(verbose_name="Total de Items", null = True, blank=True)
    cantidad_productos = models.PositiveIntegerField(verbose_name="Total de productos", null=True, blank=True)
    estado = models.CharField(verbose_name="Estado del pedido", null=True, blank=True, max_length=20)

    class Meta:
        verbose_name = "Reporte de Pedidos"
        verbose_name_plural = "Reporte de Pedidos"

    def __str__(self):
        return "ID Reporte {}".format(self.id)


#Auditoria para admin
class Registro_premium(models.Model):
    id_registro = models.ForeignKey(Tipo_usuarios, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    premium = models.PositiveIntegerField(verbose_name="Tipo de Premium", default=0, null=True, blank=True)
    fecha_inicio = models.DateField(verbose_name="Fecha de Inicio del Premium", null=True, blank=True)
    fecha_caducidad = models.DateField(verbose_name="Fecha de Caducidad del Premium", null=True, blank=True)

    class Meta:
        verbose_name = "Auditoria de premium"
        verbose_name_plural = "Auditoria de premium"

    def __str__(self):
        return "ID Registro {}".format(self.id)

#Reporte productos
#Despues de completar un pedido se tienen que ingresar datos aca
class Reporte_productos(models.Model):
    cliente = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    lista = models.PositiveIntegerField(verbose_name="ID Lista", default=0, null=True, blank=True)
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    producto = models.PositiveIntegerField(verbose_name="ID Producto", default=0, null=True, blank=True)
    nombre_producto = models.CharField(verbose_name="Nombre Producto", max_length=50, null=True, blank=True)
    cantidad = models.PositiveIntegerField(verbose_name="Cantidad Comprada", null=True, blank=True, default=0)
    oferta = models.BooleanField(verbose_name="Producto en Oferta", null=True, blank=True, default=False)
    Total = models.PositiveIntegerField(verbose_name="Total", null=True, blank=True, default=0)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)

    class Meta:
        verbose_name = "Reporte de Productos"
        verbose_name_plural = "Reporte de Productos"

    def __str__(self):
        return "ID Reporte {}".format(self.id)

#Puntaje de pedidos
class Valorizacion_pedidos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    lista = models.PositiveIntegerField(verbose_name="ID lista", default=0, null=True, blank=True)
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    puntuacion = models.PositiveIntegerField(verbose_name="Puntuacion", default=0, null=True, blank=True)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)
    comentarios = models.TextField(verbose_name="Comentarios del pedido", null=True, blank=True)

    class Meta:
        verbose_name = "Valorizacion de Pedidos"
        verbose_name_plural = "Valorizacion de Pedidos"

    def __str__(self):
        return "ID Registro {}".format(self.id)

sistema_valledor/vendedor/models.py
from django.db import models
from django.contrib.auth.models import User

#FUNCIONAES CUSTOM PARA ELIMINAR IMAGENES ANTERIORES

def borrar_imagen_anterior_producto(instance, filename):
    try:
        old_instance = Productos.objects.get(pk=instance.pk)
    except:
        old_instance=None
    if old_instance and old_instance.imagen != 'core/sin_imagen.webp':
        old_instance.imagen.delete()
    return 'vendedor/img_productos/'+filename

def borrar_imagen_anterior_local_muestra(instance, filename):
    try:
        old_instance = Local.objects.get(pk=instance.pk)
    except:
        old_instance=None
    if old_instance and old_instance.imagen_muestra != 'core/sin_imagen.webp':
        old_instance.imagen_muestra.delete()
    return 'vendedor/img_tiendas/'+filename

def borrar_imagen_anterior_local_banner(instance, filename):
    try:
        old_instance = Local.objects.get(pk=instance.pk)
    except:
        old_instance=None
    if old_instance and old_instance.imagen_banner != 'vendedor/Mi_Tienda.webp':
        old_instance.imagen_banner.delete()
    return 'vendedor/img_tiendas/'+filename

#///////////////////////////////////////////////////////////////////////////////////////

class Categoria_Productos(models.Model):
    categoria = models.CharField(verbose_name="Categoria", max_length=30, null=True, blank=True)

    class Meta:
        ordering = ['categoria']
        verbose_name ="Categoria"
        verbose_name_plural="Categorias"

    def __str__(self):
        return self.categoria

class Unidad_Medida(models.Model):
    medida_unidad = models.CharField(verbose_name="Unidad de Medida Unidad", max_length=30, null=True, blank=True)
    medida_plural = models.CharField(verbose_name="Unidad de Medida Plural", max_length=30, null=True, blank=True)

    class Meta:
        verbose_name = "Unidad de Medida"
        verbose_name_plural = "Unidades de Medidas"

    def __str__(self):
        return self.medida_unidad


# Create your models here.
class Productos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True )
    nombre = models.CharField(verbose_name="Nombre", max_length=50, null=True, blank=True)
    precio = models.PositiveIntegerField(verbose_name="Precio", null=True, blank=True, default=0)
    categoria = models.ForeignKey(Categoria_Productos, on_delete=models.CASCADE,null=True, blank=True)
    oferta = models.BooleanField(verbose_name="Producto en Oferta", null=True, blank=True, default=False)
    precio_oferta = models.PositiveIntegerField(verbose_name="Precio de la Oferta", null=True, blank=True, default=0)
    stock = models.PositiveIntegerField(verbose_name="Stock del Producto", null=True, blank=True, default=0)
    maximo_prod_comprar = models.PositiveIntegerField(verbose_name="Maximo de productos a comprar", null=True, blank=True, default=0)
    imagen = models.ImageField(upload_to=borrar_imagen_anterior_producto, null=True, blank=True, default='core/sin_imagen.webp')
    activado = models.BooleanField(verbose_name="Producto activado?", null=True, blank=True, default=True)
    unidad_medida = models.ForeignKey(Unidad_Medida, on_delete=models.CASCADE, null=True, blank=True)
    comentario = models.TextField(verbose_name="Comentarios", null=True, blank=True)

    class Meta:
        ordering = ['oferta', 'precio', 'nombre']
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.nombre

class Local(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre_local = models.CharField(verbose_name="Nombre del Local", max_length=50, null=True, blank=True)
    ubicacion_local = models.CharField(verbose_name="Ubicacion del Local", max_length=100, null=True, blank=True)
    imagen_muestra = models.ImageField(verbose_name="Imagen de muestra", upload_to=borrar_imagen_anterior_local_muestra, default='core/sin_imagen.webp', null=True, blank=True)
    imagen_banner = models.ImageField(verbose_name="Imagen de Banner", upload_to=borrar_imagen_anterior_local_banner,default='vendedor/Mi_Tienda.webp', null=True, blank=True)
    activado = models.BooleanField(verbose_name="Local activado?", null=True, blank=True, default=True)

    class Meta:
        ordering=['nombre_local']
        verbose_name = "Local"
        verbose_name_plural = "Locales"

    def __str__(self):
        return self.nombre_local

class Oferta(models.Model):
    tipos_de_ofertas = (('general', 'Oferta General'), ('temporada', 'Oferta de Temporada'), ('rango_plata', 'Oferta para clientes de rango plata'),
                        ('rango_oro', 'Oferta para clientes de rango oro'), ('rango_diamante', 'Oferta para clientes de rango diamante'), ('convencional','Oferta Convencional'))
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    oferta = models.CharField(verbose_name="Oferta", null=True, blank=True, max_length=100)
    tipo_oferta = models.CharField(verbose_name="Tipo de Oferta", null = True, blank = True, max_length=30, choices=tipos_de_ofertas)
    activado = models.BooleanField(verbose_name="Oferta activada?", null=True, blank=True, default=True)

    class Meta:
        ordering = ['tipo_oferta']
        verbose_name = "Oferta"
        verbose_name_plural = "Ofertas"

    def __str__(self):
        return self.oferta

class Puntos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    puntos = models.PositiveIntegerField(verbose_name="Total de puntos", null=True, blank=True, default=0)
    local = models.ForeignKey(Local, on_delete=models.CASCADE,null=True, blank=True)
    tipo_cuenta = models.CharField(verbose_name="Tipo de cuenta", null=True, blank=True, max_length=30)

    class Meta:
        ordering = ['user']
        verbose_name = "Puntos"
        verbose_name_plural = "Puntos"

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.tipo_cuenta)

#Auditoria para vendedor
class Registro_auditoria_productos(models.Model):
    producto = models.PositiveIntegerField(verbose_name="ID Producto", default=0, null=True, blank=True)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre_producto = models.CharField(verbose_name="Nombre Producto", max_length=200, null=True, blank=True)
    accion = models.CharField(verbose_name="Accion", max_length=30, null=True, blank=True)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)

    class Meta:
        verbose_name = "Auditoria de Productos"
        verbose_name_plural = "Auditoria de Productos"

    def __str__(self):
        return "Registro ID {}".format(self.id)

sistema_valledor/cliente/templates/cliente/agregar_lista.html
{%extends 'core/base.html'%}
{%block title%}Crear Lista{%endblock%}
{%block content%}
<div class="container shadow container-whithe">
    <div class="row">
        <div class="col-12 pt-4 pb-1 text-center">
            <h2>Seccion de creación de listas</h2>
            <p><em>Aquí puedes crear tus listas de compras.</em></p>
            <hr>
        </div>
        <!--ALERTS-->
        <div class="col-12 text-center">
            {%if request.GET.msg == 'form_no_valid'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> No se pudo crear la lista, inténtelo otra vez.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%endif%}
        </div>
    </div>
    <!--FIN ALERTS-->
    <form action="" class="row justify-content-center" method="POST" onsubmit="return validar_lista_agregar();" enctype="multipart/form-data">
        {%csrf_token%}
        <input type="hidden" name="user" id="id_user" value="{{request.user.id}}">
        <div class="col-12 col-sm-4 form-group">
            {{form.nombre.label}}
            {{form.nombre}}
            <div class="invalid-feedback">
                <p id="id_nombre-invalid" class="m-0"></p>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-sm-4 form-group">
            {{form.local.label}}
            {%if request.GET.nombre%}
            <p class="m-0 color-rojo"><strong>Selecciona el local "{{request.GET.nombre}}"</strong></p>
            {%endif%}
            <select name="local" class="form-control" id="id_local">
                <option value="" selected>---------</option>
            {%for tienda in tiendas%}
                {%if tienda.nombre_local != 'Sin definir'%}
                <option value="{{tienda.id}}">{{tienda.nombre_local}}</option>
                {%endif%}
            {%endfor%}
            </select>
            <div class="invalid-feedback">
                <p id="id_local-invalid" class="m-0"></p>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-sm-4 form-group">
             {{form.comentario_cliente.label}}
             {{form.comentario_cliente}}
             <div class="invalid-feedback">
                <p id="id_comentario_cliente-invalid" class="m-0"></p>
            </div>
        </div>
        <div class="w-100"></div>

        <div class="col-12 form-group text-center mt-3">
            <button type="submit" class="btn btn-success"><span data-icon="v"></span> Agregar</button>
        </div>
    </form>
    <div class="row justify-content-center">
        <div class="col-12 m-4">
            <a href="{%url 'cliente:mis_listas' request.user.id%}" class="btn btn-secondary "><span data-icon="x"></span> Volver</a>
        </div>
    </div>
</div>
{%endblock%}

sistema_valledor/cliente/templates/cliente/detalle_productos.html
{%extends 'core/base.html'%}
{%block title%}Detalle {{object.nombre}}{%endblock%}
{%block content%}
<div class="container shadow container-whithe">
    <div class="row pt-3 pb-5 p-md-5">

        <div class="col-md-4 col-12 text-center">
            <img src="{{object.imagen.url}}" class="img-fluid img-thumbnail" alt="producto_{{object.nombre}}">
        </div>

        <div class="col-md-8 col-12 pt-md-0 pt-4">
            <h3 class="pb-2"><strong>{{object.nombre}}</strong></h3>

            <h5><strong>Tienda</strong></h5>
            <p>{{local.nombre_local}} <a href="{%url 'cliente:detalle_locales' object.user.id%}" class="badge badge-info">Visitar tienda!</a></p>

            {%if object.oferta is False%}
            <p class="mb-0"><strong>Precio</strong></p>
            <p>${{object.precio}} x {{object.unidad_medida}}</p>
            {%else%}
            <p class="mb-0"><strong class="color-rojo">Precio Oferta!</strong></p>
            <p class="color-rojo">${{object.precio_oferta}} x {{object.unidad_medida}}</p>
            {%endif%}

            {%if object.oferta%}
            <p class="mb-0 text-muted"><strong>Precio normal</strong></p>
            <p><strike>${{object.precio}}</strike></p>
            {%endif%}

            <p class="mb-0"><strong>Stock</strong></p>
            <p>{{object.stock}} {{object.unidad_medida.medida_plural}}</p>

            <p class="mb-0"><strong>Categoría</strong></p>
            <p><em>{{object.categoria}}</em></p>


            <p class="mb-0"><strong>Comentarios del productos</strong></p>
            {%if object.Comentario%}
            <p>{{object.Comentario}}</p>
            {%else%}
            <p>No se cuenta con descripción el producto</p>
            {%endif%}
            <!--ALERTS-->
            {%if request.GET.msg == 'form_no_valid'%}
            <div class="alert alert-danger alert-dismissible fade show text-center col-12 col-md-10" role="alert">
              <span class="icon-exclamation-triangle"></span> <strong>No se pudo agregar el producto, inténtelo otra vez.</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%elif request.GET.msg == 'error_cantidad'%}
            <div class="alert alert-danger alert-dismissible fade show text-center col-12 col-md-10" role="alert">
              <span class="icon-exclamation-triangle"></span> <strong>Ya tienes 15 productos en la lista escogida, escoge o crea otra lista</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%elif request.GET.msg == 'error_duplicado'%}
            <div class="alert alert-danger alert-dismissible fade show text-center col-12 col-md-10" role="alert">
              <span class="icon-exclamation-triangle"></span> <strong>No puedes tener repetidos 5 veces el mismo producto en una lista</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%elif request.GET.msg == 'form_ok'%}
            <div class="alert alert-success alert-dismissible fade show col-12 col-md-10 text-center" role="alert">
              <strong><span class="icon-angellist"></span> Producto agregado exitosamente!
              <a href="{%url 'cliente:mis_listas' request.user.id%}" class="btn btn-success btn-sm">Ir a Listas</a>
              </strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%endif%}
            <!--FIN ALERTS-->
            {%if tipo.tipo_usuario == 'cliente'%}
                <form action="" method="POST" class="col-12 col-md-10 p-3 rounded shadow" onsubmit="return validar_agregar_listas()">
                    {%csrf_token%}
                    <h4 class="mb-3 color-base text-center"><strong>Agregar producto a una lista</strong></h4>
                    <a href="{%url 'cliente:mis_listas' request.user.id%}" class="btn btn-primary btn-sm mb-2">Mis Listas</a>
                    <input type="hidden" name="user" id="id_user" value="{{request.user.id}}">
                    <input type="hidden" name="productos" id="id_productos" value="{{object.id}}">
                    <input type="hidden" name="local" id="id_local" value="{{local.id}}">
                    <input type="hidden" name="precio_producto" id="id_precio_producto"
                    {%if object.oferta%}
                           value="{{object.precio_oferta}}"
                    {%else%}
                           value="{{object.precio}}"
                    {%endif%}
                    >
                    {%if listas%}
                    <div class="col-12 form-group p-0">
                        <label>Escoja la lista</label>
                        <select name="lista" class="form-control" id="id_lista">
                          <option value="" selected="">---------</option>
                          {%for lista in listas%}
                          <option value="{{lista.id}}">{{lista.nombre}}</option>
                          {%endfor%}
                        </select>
                        <div class="invalid-feedback">
                            <p id="id_lista-invalid" class="m-0"></p>
                        </div>
                        <p class="small color-rojo" hidden id="id_texto_emergencia">Para agregar un producto se necesita una lista</p>
                    </div>

                    <div class="col-12 form-group p-0">
                        <label>Cantidad a agregar</label>
                        {{form.cantidad}}
                        <div class="invalid-feedback">
                            <p id="id_cantidad-invalid" class="m-0"></p>
                        </div>
                    </div>

                    <div class="col-12 form-group p-0">
                        <label>Comentarios del producto</label>
                        {{form.comentarios}}
                    </div>

                    <div class="col-12 form-group p-0 text-center">
                        <input type="submit" class="btn btn-success mb-2" value="Agregar a la lista">
                        <p class="mb-2">o si deseas puedes</p>
                        <a href="{%url 'cliente:agregar_lista'%}?nombre={{local.nombre_local}}" class="btn btn-primary">Crear una lista para esta tienda</a>
                    </div>
                    {%else%}
                    <p class="text-center"><strong>No tienes una lista válida para esta tienda, ve a crear una!</strong></p>
                    <div class="col-12 form-group p-0 text-center">
                        <a href="{%url 'cliente:agregar_lista'%}?nombre={{local.nombre_local}}" class="btn btn-primary">Crear una lista para esta tienda</a>
                    </div>
                    {%endif%}
                </form>
            {%endif%}
        </div>
        <div class="col-12 pt-4">
            <a href="{%url 'cliente:listar_productos'%}" class="btn btn-secondary "><span data-icon="x"></span> Volver</a>
        </div>
    </div>
</div>
{%endblock%}

sistema_valledor/cliente/templates/cliente/eliminar_lista.html
{%extends 'core/base.html'%}
{%block title%}Eliminar "{{lista.nombre}}"{%endblock%}
{%block content%}
<div class="container shadow container-whithe">

    <div class="row justify-content-center">
        <div class="col-12 pt-4 pb-4 text-center">
            <h2 class="pb-3">¿Estás seguro de querer eliminar "{{lista.nombre}}"?</h2>
            <hr class="pb-3">
            {%if request.GET.msg == 'elim_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> No se pudo eliminar la lista, inténtelo otra vez.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%endif%}
        </div>

        <img src="/media/core/papelera.webp" alt="simbolo_eliminar" width="200px">

        <div class="col-12 text-center pt-4 pb-5">
            <form method="POST">
                {%csrf_token%}
                <button type="submit" class="btn btn-danger"><span class="icon-trash-b"> Si, la quiero borrar de todos modos</span></button>
            </form>
        </div>

        <div class="col-12 m-4 pt-5">
            <a href="{%url 'cliente:mis_listas' request.user.id%}" class="btn btn-secondary "><span data-icon="x"></span> Volver</a>
        </div>
    </div>
</div>
{%endblock%}