sistema_valledor/core/urls.py
from django.urls import path
from .views import index,contactanos

core_patterns = ([
path("",index, name = "index"),
path("contactanos/",contactanos, name = "contactanos"),
],'core')

sistema_valledor/sistema_valledor/urls.py
from django.contrib import admin
from django.urls import path, include
from core.urls import core_patterns
from registration.urls import registration_urlpatterns
from vendedor.urls import vendedor_urlpatterns
from cliente.urls import cliente_urlpatterns
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include(registration_urlpatterns)),
    path('cliente/', include(cliente_urlpatterns)),
    path('vendedor/', include(vendedor_urlpatterns)),
    path('',include(core_patterns)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

sistema_valledor/vendedor/urls.py
from django.urls import path
from .views import Listar_Productos, Agregar_Productos, Actualizar_Productos, Eliminar_Productos, Panel_de_vendedor, \
    Detalle_Local, Actualizar_Local, Panel_Listas, Detalle_Listas, Revisar_Listas, Mis_Ofertas, Agregar_Ofertas,\
    Actualizar_Ofertas, Eliminar_Ofertas,Detalle_pedidos_success, Reportes_Premium,\
    Reporte_Productos, Seleccion_Reportes, Contacto_vendedor

vendedor_urlpatterns = ([
    path('contacto_vendedor/', Contacto_vendedor, name = "contacto_vendedor"),
    path('panel_de_vendedor/<int:id>/', Panel_de_vendedor, name = "panel_de_vendedor"),
    path('lista_productos/<int:id>/',Listar_Productos, name = "listar_productos"),
    path('agregar_productos/<int:id>/', Agregar_Productos, name="agregar_productos"),
    path('actualizar_productos/<int:id>/', Actualizar_Productos, name = "actualizar_productos"),
    path('eliminar_productos/<int:id>/', Eliminar_Productos, name = "eliminar_productos"),
    path('mi_tienda/<int:id>/',Detalle_Local, name = "mi_tienda"),
    path('actualizar_mi_tienda/<int:id>/', Actualizar_Local, name = "actualizar_mi_tienda"),
    path('mis_pedidos/<int:id>/', Panel_Listas, name = "mis_pedidos"),
    path('detalle_mis_pedidos/<int:id>/', Detalle_Listas, name = "detalle_mis_pedidos"),
    path('success_detalle_mis_pedidos/<int:id>/', Detalle_pedidos_success, name = "success_detalle_mis_pedidos"),
    path('revisar_mis_pedidos/<int:id>/', Revisar_Listas, name = "revisar_mis_pedidos"),
    path('mis_ofertas/<int:id>/', Mis_Ofertas, name="mis_ofertas"),
    path('agregar_oferta/<int:id>/',Agregar_Ofertas, name = "agregar_oferta"),
    path('actualizar_oferta/<int:id_oferta>/',Actualizar_Ofertas, name = "actualizar_oferta"),
    path('eliminar_oferta/<int:id_oferta>/',Eliminar_Ofertas, name = "eliminar_oferta"),
    path('reporte_admin/' , Reportes_Premium, name = "reporte_admin"),
    path('reporte_productos/<int:id_user>/', Reporte_Productos, name = "reporte_productos"),
    path('seccion_reportes/<int:id_user>/', Seleccion_Reportes, name = "reportes"),
], 'vendedor')

sistema_valledor/cliente/models.py
#Inicial
from django.db import models
from vendedor.models import Local, Productos
#Traer el modelo de Usuarios
from django.contrib.auth.models import User
from registration.models import Tipo_usuarios

# Create your models here.
class Listas(models.Model):
    estados_de_listas = (('lista_retiro', 'Listo para retirar'), ('armando_pedido', 'Armando Pedido'), ('normal', 'Normal'),
                         ('enviada', 'Enviada'), ('cancelada', 'Cancelada'),
                          ('no_retirada', 'No retirada'),('completada', 'Lista completada'))
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre = models.CharField(verbose_name="Nombre de la lista", null=True, blank=True, max_length=50)
    total = models.PositiveIntegerField(verbose_name="Total de la lista", null=True, blank=True, default=0)
    fecha_enviado = models.DateField(verbose_name="Fecha de envio de la lista", null=True, blank=True)
    fecha_expiracion = models.DateField(verbose_name="Fecha de expiracion de la lista", null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(verbose_name="Fecha de actualizacion de la lista", null=True, blank=True, auto_now=True)
    comentario_cliente = models.TextField(verbose_name="Comentario de cliente", null=True, blank=True)
    comentario_vendedor = models.TextField(verbose_name="Comentario de vendedor", null=True, blank=True)
    estado_lista = models.CharField(verbose_name="Estado de la lista", max_length=20, null=True, blank=True, choices=estados_de_listas, default='normal')
    cancelaciones = models.PositiveIntegerField(verbose_name = "Veces restantes a cancelar la lista", null=True, blank=True, default=5)
    total_marcado = models.PositiveIntegerField(verbose_name="Total de los productos marcados", null=True, blank=True, default=0)
    valorizacion = models.BooleanField(verbose_name="Fue Valorizada?",null= True, blank=True, default=False)

    class Meta:
        verbose_name = "Listas"
        verbose_name_plural = "Listas"

    def __str__(self):
        return self.nombre

class Productos_listas(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True )
    productos = models.ForeignKey(Productos, on_delete=models.CASCADE, null=True, blank=True )
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True )
    lista = models.ForeignKey(Listas, on_delete=models.CASCADE, null=True, blank=True )
    cantidad = models.PositiveIntegerField(verbose_name="Cantidad a comprar", null=True, blank=True, default=0)
    comentarios = models.TextField(verbose_name="Comentarios del productos a comprar", null=True, blank=True)
    precio_producto = models.PositiveIntegerField(verbose_name="Precio actual del producto a comprar", null=True, blank=True, default=0)
    producto_marcado = models.BooleanField(verbose_name="Producto marcado", null=True, blank=True, default=False)
    oferta = models.BooleanField(verbose_name="Producto en Oferta", null=True, blank=True, default=False)

    class Meta:
        verbose_name = "Producto de la lista"
        verbose_name_plural = "Productos de las listas"

    def __str__(self):
        return "{}, perteneciente al local {}".format(self.productos.nombre, self.local.nombre_local)

#Reporteria para clientes
class Reporte_listas(models.Model):
    lista = models.PositiveIntegerField(verbose_name="ID lista", default=0, null=True, blank=True)
    local = models.ForeignKey(Local, on_delete= models.CASCADE, null = True, blank = True)
    nombre_lista = models.CharField(verbose_name="Nombre de la lista", max_length=50, null=True, blank=True)
    cliente = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)
    total = models.PositiveIntegerField(verbose_name="Total del pedido", null = True, blank=True)
    cantidad_items = models.PositiveIntegerField(verbose_name="Total de Items", null = True, blank=True)
    cantidad_productos = models.PositiveIntegerField(verbose_name="Total de productos", null=True, blank=True)
    estado = models.CharField(verbose_name="Estado del pedido", null=True, blank=True, max_length=20)

    class Meta:
        verbose_name = "Reporte de Pedidos"
        verbose_name_plural = "Reporte de Pedidos"

    def __str__(self):
        return "ID Reporte {}".format(self.id)


#Auditoria para admin
class Registro_premium(models.Model):
    id_registro = models.ForeignKey(Tipo_usuarios, on_delete=models.CASCADE, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    premium = models.PositiveIntegerField(verbose_name="Tipo de Premium", default=0, null=True, blank=True)
    fecha_inicio = models.DateField(verbose_name="Fecha de Inicio del Premium", null=True, blank=True)
    fecha_caducidad = models.DateField(verbose_name="Fecha de Caducidad del Premium", null=True, blank=True)

    class Meta:
        verbose_name = "Auditoria de premium"
        verbose_name_plural = "Auditoria de premium"

    def __str__(self):
        return "ID Registro {}".format(self.id)

#Reporte productos
#Despues de completar un pedido se tienen que ingresar datos aca
class Reporte_productos(models.Model):
    cliente = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    lista = models.PositiveIntegerField(verbose_name="ID Lista", default=0, null=True, blank=True)
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    producto = models.PositiveIntegerField(verbose_name="ID Producto", default=0, null=True, blank=True)
    nombre_producto = models.CharField(verbose_name="Nombre Producto", max_length=50, null=True, blank=True)
    cantidad = models.PositiveIntegerField(verbose_name="Cantidad Comprada", null=True, blank=True, default=0)
    oferta = models.BooleanField(verbose_name="Producto en Oferta", null=True, blank=True, default=False)
    Total = models.PositiveIntegerField(verbose_name="Total", null=True, blank=True, default=0)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)

    class Meta:
        verbose_name = "Reporte de Productos"
        verbose_name_plural = "Reporte de Productos"

    def __str__(self):
        return "ID Reporte {}".format(self.id)

#Puntaje de pedidos
class Valorizacion_pedidos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    lista = models.PositiveIntegerField(verbose_name="ID lista", default=0, null=True, blank=True)
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    puntuacion = models.PositiveIntegerField(verbose_name="Puntuacion", default=0, null=True, blank=True)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)
    comentarios = models.TextField(verbose_name="Comentarios del pedido", null=True, blank=True)

    class Meta:
        verbose_name = "Valorizacion de Pedidos"
        verbose_name_plural = "Valorizacion de Pedidos"

    def __str__(self):
        return "ID Registro {}".format(self.id)

sistema_valledor/vendedor/models.py
from django.db import models
from django.contrib.auth.models import User

#FUNCIONAES CUSTOM PARA ELIMINAR IMAGENES ANTERIORES

def borrar_imagen_anterior_producto(instance, filename):
    try:
        old_instance = Productos.objects.get(pk=instance.pk)
    except:
        old_instance=None
    if old_instance and old_instance.imagen != 'core/sin_imagen.webp':
        old_instance.imagen.delete()
    return 'vendedor/img_productos/'+filename

def borrar_imagen_anterior_local_muestra(instance, filename):
    try:
        old_instance = Local.objects.get(pk=instance.pk)
    except:
        old_instance=None
    if old_instance and old_instance.imagen_muestra != 'core/sin_imagen.webp':
        old_instance.imagen_muestra.delete()
    return 'vendedor/img_tiendas/'+filename

def borrar_imagen_anterior_local_banner(instance, filename):
    try:
        old_instance = Local.objects.get(pk=instance.pk)
    except:
        old_instance=None
    if old_instance and old_instance.imagen_banner != 'vendedor/Mi_Tienda.webp':
        old_instance.imagen_banner.delete()
    return 'vendedor/img_tiendas/'+filename

#///////////////////////////////////////////////////////////////////////////////////////

class Categoria_Productos(models.Model):
    categoria = models.CharField(verbose_name="Categoria", max_length=30, null=True, blank=True)

    class Meta:
        ordering = ['categoria']
        verbose_name ="Categoria"
        verbose_name_plural="Categorias"

    def __str__(self):
        return self.categoria

class Unidad_Medida(models.Model):
    medida_unidad = models.CharField(verbose_name="Unidad de Medida Unidad", max_length=30, null=True, blank=True)
    medida_plural = models.CharField(verbose_name="Unidad de Medida Plural", max_length=30, null=True, blank=True)

    class Meta:
        verbose_name = "Unidad de Medida"
        verbose_name_plural = "Unidades de Medidas"

    def __str__(self):
        return self.medida_unidad


# Create your models here.
class Productos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True )
    nombre = models.CharField(verbose_name="Nombre", max_length=50, null=True, blank=True)
    precio = models.PositiveIntegerField(verbose_name="Precio", null=True, blank=True, default=0)
    categoria = models.ForeignKey(Categoria_Productos, on_delete=models.CASCADE,null=True, blank=True)
    oferta = models.BooleanField(verbose_name="Producto en Oferta", null=True, blank=True, default=False)
    precio_oferta = models.PositiveIntegerField(verbose_name="Precio de la Oferta", null=True, blank=True, default=0)
    stock = models.PositiveIntegerField(verbose_name="Stock del Producto", null=True, blank=True, default=0)
    maximo_prod_comprar = models.PositiveIntegerField(verbose_name="Maximo de productos a comprar", null=True, blank=True, default=0)
    imagen = models.ImageField(upload_to=borrar_imagen_anterior_producto, null=True, blank=True, default='core/sin_imagen.webp')
    activado = models.BooleanField(verbose_name="Producto activado?", null=True, blank=True, default=True)
    unidad_medida = models.ForeignKey(Unidad_Medida, on_delete=models.CASCADE, null=True, blank=True)
    comentario = models.TextField(verbose_name="Comentarios", null=True, blank=True)

    class Meta:
        ordering = ['oferta', 'precio', 'nombre']
        verbose_name = "Producto"
        verbose_name_plural = "Productos"

    def __str__(self):
        return self.nombre

class Local(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre_local = models.CharField(verbose_name="Nombre del Local", max_length=50, null=True, blank=True)
    ubicacion_local = models.CharField(verbose_name="Ubicacion del Local", max_length=100, null=True, blank=True)
    imagen_muestra = models.ImageField(verbose_name="Imagen de muestra", upload_to=borrar_imagen_anterior_local_muestra, default='core/sin_imagen.webp', null=True, blank=True)
    imagen_banner = models.ImageField(verbose_name="Imagen de Banner", upload_to=borrar_imagen_anterior_local_banner,default='vendedor/Mi_Tienda.webp', null=True, blank=True)
    activado = models.BooleanField(verbose_name="Local activado?", null=True, blank=True, default=True)

    class Meta:
        ordering=['nombre_local']
        verbose_name = "Local"
        verbose_name_plural = "Locales"

    def __str__(self):
        return self.nombre_local

class Oferta(models.Model):
    tipos_de_ofertas = (('general', 'Oferta General'), ('temporada', 'Oferta de Temporada'), ('rango_plata', 'Oferta para clientes de rango plata'),
                        ('rango_oro', 'Oferta para clientes de rango oro'), ('rango_diamante', 'Oferta para clientes de rango diamante'), ('convencional','Oferta Convencional'))
    local = models.ForeignKey(Local, on_delete=models.CASCADE, null=True, blank=True)
    oferta = models.CharField(verbose_name="Oferta", null=True, blank=True, max_length=100)
    tipo_oferta = models.CharField(verbose_name="Tipo de Oferta", null = True, blank = True, max_length=30, choices=tipos_de_ofertas)
    activado = models.BooleanField(verbose_name="Oferta activada?", null=True, blank=True, default=True)

    class Meta:
        ordering = ['tipo_oferta']
        verbose_name = "Oferta"
        verbose_name_plural = "Ofertas"

    def __str__(self):
        return self.oferta

class Puntos(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    puntos = models.PositiveIntegerField(verbose_name="Total de puntos", null=True, blank=True, default=0)
    local = models.ForeignKey(Local, on_delete=models.CASCADE,null=True, blank=True)
    tipo_cuenta = models.CharField(verbose_name="Tipo de cuenta", null=True, blank=True, max_length=30)

    class Meta:
        ordering = ['user']
        verbose_name = "Puntos"
        verbose_name_plural = "Puntos"

    def __str__(self):
        return "{} {}".format(self.user.first_name, self.tipo_cuenta)

#Auditoria para vendedor
class Registro_auditoria_productos(models.Model):
    producto = models.PositiveIntegerField(verbose_name="ID Producto", default=0, null=True, blank=True)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    nombre_producto = models.CharField(verbose_name="Nombre Producto", max_length=200, null=True, blank=True)
    accion = models.CharField(verbose_name="Accion", max_length=30, null=True, blank=True)
    fecha_registro = models.DateField(verbose_name="Fecha de registro", null=True, blank=True)

    class Meta:
        verbose_name = "Auditoria de Productos"
        verbose_name_plural = "Auditoria de Productos"

    def __str__(self):
        return "Registro ID {}".format(self.id)

sistema_valledor/vendedor/templates/vendedor/actualizar_oferta.html
{%extends 'core/base.html'%}
{%block title%}Actualizar Ofertas{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-12 p-0">
            <img src="/media/vendedor/Mis_ofertas.webp" alt="alt_mis_ofertas" class="img-fluid">
        </div>
    </div>
</div>
<div class="container container-whithe shadow">
    <div class="row justify-content-center pb-4">
        <!--TITULO-->
        <div class="col-12 text-center pt-3">
            <h2>Actualizar ofertas</h2>
            <p>Aquí podrás actualizar o editar tus ofertas de la forma que quieras</p>
            <hr>
        </div>
        <!--FIN TITULO-->
        <!--ALERTS-->
        <div class="col-12 text-center">
            {%if request.GET.msg == 'act_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> <strong>No se pudo actualizar la oferta, intentelo otra vez.</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%elif request.GET.msg == 'act_user_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span><strong>No puede actualizar una oferta diferente a esta.</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%elif request.GET.msg == 'premium_error' or request.GET.msg == 'general_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> <strong>No tiene suscripción para poder editar esta oferta.</strong>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%endif%}
        </div>
        <!--FIN ALERTS-->
    </div>

    <!--CONTENIDO-->
    <form action="" class="row justify-content-center" onsubmit="return validar_agregar_ofertas()" method="POST">
        {%csrf_token%}
        {{form.local}}
        <div class="col-12 col-md-6 form-group">
            <label>Oferta a mostrar</label>
            {{form.oferta}}
            <div class="invalid-feedback">
                <p id="id_oferta-invalid" class="m-0"></p>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-md-6 form-group">
            <label>Tipo de oferta</label>
            <select name="tipo_oferta" class="form-control" id="id_tipo_oferta">
              <option value="">---------</option>
              {%if tipo.tipo_premium != 0%}

              <option value="general" {%if tipo_oferta == 'general'%} selected {%endif%}>Oferta General</option>

              <option value="temporada" {%if tipo_oferta == 'temporada'%} selected {%endif%}>Oferta de Temporada</option>
              {%endif%}
              <option value="rango_plata" {%if tipo_oferta == 'rango_plata'%} selected {%endif%}>Oferta para clientes de rango plata</option>

              <option value="rango_oro" {%if tipo_oferta == 'rango_oro'%} selected {%endif%}>Oferta para clientes de rango oro</option>

              <option value="rango_diamante" {%if tipo_oferta == 'rango_diamante'%} selected {%endif%}>Oferta para clientes de rango diamante</option>

              <option value="convencional"{%if tipo_oferta == 'convencional'%} selected {%endif%}>Oferta Convencional</option>
            </select>
            <div class="invalid-feedback">
                <p id="id_tipo_oferta-invalid" class="m-0"></p>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-md-6 form-group">
            <label>Oferta activada?</label>
            {{form.activado}}
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-md-6 text-center pb-5">
            <button type="submit" value="Actualizar Oferta" class="btn btn-primary"><span data-icon="u"></span> Actualizar Oferta</button>
        </div>
        <div class="col-12 m-4">
            <a href="{%url 'vendedor:mis_ofertas' request.user.id%}" class="btn btn-secondary "><span data-icon="x"></span> Volver</a>
        </div>
    </form>
    <!--FIN CONTENIDO-->

</div>
{%endblock%}

sistema_valledor/vendedor/templates/vendedor/agregar_oferta.html
{%extends 'core/base.html'%}
{%block title%}Agregar Oferta{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-12 p-0">
            <img src="/media/vendedor/Mis_ofertas.webp" alt="alt_mis_ofertas" class="img-fluid">
        </div>
    </div>
</div>
<div class="container container-whithe shadow">
    <!--TITULO-->
    <div class="row pb-4 justify-content-center">
        <div class="col-12 text-center pt-3">
            <h2>Agregar una oferta al local</h2>
            <p>Aquí puedes agregar <strong>ofertas para que captes más publico</strong>, recuerda que puedes crear ofertas ahora y activarlas más tarde.</p>
            <hr>
        </div>
         <!--ALERTS-->
        <div class="col-12 text-center">
            {%if request.GET.msg == 'form_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> No se pudo agregar la oferta, inténtelo otra vez.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%elif request.GET.msg == 'general_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> No se pudo agregar la oferta, inténtelo otra vez.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%elif request.GET.msg == 'premium_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> No se pudo agregar la oferta, inténtelo otra vez.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%endif%}
        </div>
        <!--FIN ALERTS-->
    </div>
    <!--FIN TITULO-->
    <!--CONTENIDO-->
    <form action="" class="row justify-content-center" onsubmit="return validar_agregar_ofertas()" method="POST">
        {%csrf_token%}
        <input type="hidden" value="{{local.id}}" id="local_id" name="local">
        <div class="col-12 col-md-6 form-group">
            <label>Oferta a mostrar</label>
            {{form.oferta}}
            <div class="invalid-feedback">
                <p id="id_oferta-invalid" class="m-0"></p>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-md-6 form-group">
            <label>Tipo de oferta</label>
            <select name="tipo_oferta" class="form-control" id="id_tipo_oferta">
              <option value="" selected="">---------</option>
              {%if tipo.tipo_premium != 0%}
              <option value="general">Oferta General</option>

              <option value="temporada">Oferta de Temporada</option>
              {%endif%}
              <option value="rango_plata">Oferta para clientes de rango plata</option>

              <option value="rango_oro">Oferta para clientes de rango oro</option>

              <option value="rango_diamante">Oferta para clientes de rango diamante</option>

              <option value="convencional">Oferta Convencional</option>
            </select>
            <div class="invalid-feedback">
                <p id="id_tipo_oferta-invalid" class="m-0"></p>
            </div>
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-md-6 form-group">
            <label>Oferta activada?</label>
            {{form.activado}}
        </div>
        <div class="w-100"></div>
        <div class="col-12 col-md-6 text-center pb-5">
            <button type="submit" value="Agregar Oferta" class="btn btn-success"><span data-icon="v"></span> Agregar Oferta</button>
        </div>
        <div class="col-12 m-4">
            <a href="{%url 'vendedor:mis_ofertas' request.user.id%}" class="btn btn-secondary "><span data-icon="x"></span> Volver</a>
        </div>
    </form>
        <!--FIN CONTENIDO-->
</div>
{%endblock%}

sistema_valledor/vendedor/templates/vendedor/eliminar_producto.html
{%extends 'core/base.html'%}
{%block title%}Eliminar producto{%endblock%}
{%block content%}
<div class="container container-whithe shadow-sm">
    <div class="row pt-3 pb-3">
        <div class="col-12 pt-3 pb-5 text-center">
            <h2>¿Estás seguro de querer eliminar "{{producto.nombre}}"?</h2>
            <p><em>Recuerda que puedes desactivar un producto en vez de eliminarlo, así te ahorraras la tarea de volver a agregarlo.</em></p>
            <hr>
            <img src="/media/core/papelera.webp" alt="simbolo_eliminar" width="200px">
            {%if request.GET.msg == 'elim_error'%}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              <span class="icon-exclamation-triangle"></span> No se pudo eliminar el producto, inténtelo otra vez.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {%endif%}
        </div>

        <div class="col-12 text-center pb-5">
            <form method="POST">
                {%csrf_token%}
                <button type="submit" class="btn btn-danger"><span class="icon-trash-b"> Si, lo quiero borrar de todos modos</span></button>
            </form>
        </div>

        <div class="col-12 m-4 pb-3">
            <a href="{%url 'vendedor:listar_productos' request.user.id%}" class="btn btn-secondary "><span data-icon="x"></span> Volver</a>
        </div>
    </div>

</div>
{%endblock%}